- Jenkinsfile
Adds a Jenkinsfile for pay-publicauth.
Immediately before merging, the following Jenkins jobs need to be disabled and deleted:
- trigger-pay-publicauth-master
- trigger-pay-publicauth-pull-request
- build-pay-publicauth
- deploy-publicauth
In addition, pay-chef needs to be modified to ensure the above jobs are not recreated.
Once this merged, existing branches will need a Jenkinsfile to get the full CI experience (new branches will inherit the one from master, of course).
> PP-1867 Add jenkinsfile

- src/test/java/uk/gov/pay/publicauth/utils/PostgresContainer.java
- Change postgres local image logging from `syslog` to `json-file` so logs can be retrieved.
> PP-2271 Use json-file as docker login rather than syslog for postgres

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/healthcheck/DatabaseHealthCheck.java
It uses jdbi, so there was already a healthcheck for the database.
Which is why there was not an explicit db healthcheck.
However I needed to customise it to add metrics. Which means we needed a custom
db healthcheck.
Other than that, this does the same thing as the other apps, it just registers
some metrics and then pulls in the new data for the metrics whenever the healthcheck is called.
> PP-2032: Add database metrics to pay-publicauth

- pom.xml
This was pulled by a transitive dependency of liquibase, although they themselves doesn't need it
> PP-2017 remove jstl dependency

- src/main/resources/migrations.xml
- This PR adds a new column to the tokens table, `token_type`, which can be of type `CARD` or `DIRECT_DEBIT`. The type has to be specified when storing (creating) the token.
> PP-2888 Add token_type column to tokens table

- src/main/java/uk/gov/pay/publicauth/auth/Token.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/model/TokenPaymentType.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoTest.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceITest.java
- src/test/java/uk/gov/pay/publicauth/model/TokenPaymentTypeTest.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- We are introducing a new payment type, direct debit. Currently we plan  to associate a gateway_account to one of the two payment types.
- This PR adds a new column to the tokens table, `token_type`, which can be of type `CREDIT_CARD` or `DIRECT_DEBIT`. The type has to be specified when storing (creating) the token.
- For backwards compatibility, if there's no `token_type` field in the token creation request payload, the type is defaulting to `CREDIT_CARD`.
- This PR follows https://github.com/alphagov/pay-publicauth/pull/67, which has the actual db migration
- This PR follows #67, which has the actual db migration
> PP-2888 Add token_type support

- src/main/resources/migrations.xml
This PR adds a new column to the tokens table, token_type, which can be of type CARD or DIRECT_DEBIT. 
We previously merged https://github.com/alphagov/pay-publicauth/pull/67 which introduced a performance issue on staging when backfilling the data, due to the high number of tokens in staging/prod created by smoke tests. 
At the moment, we are *not* backfilling the data.
> PP-2888 Add token_type to tokens table (again)

- src/main/java/uk/gov/pay/publicauth/auth/Token.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoTest.java
- Working on the wrong assumption that the token_type is embedded in the token.
This PR retrieves the token_type from the db, where it is stored, together
with account_id
> PP-2888 Retrieve token_type from the db when authorising account

- src/main/java/uk/gov/pay/publicauth/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/resources/config/config.yaml
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceITest.java
- Propagating the `X-Request-Id` header coming from nginx in each log line, via MDC
- Removing colors from logs, as they are not visible where we store our logs anyway
- Adding some additional log lines to explain what publicauth is actually doing
> PP-3065 Better logging in publicauth

- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoTest.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceITest.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
Use Java 8 time API instead of joda-time.
We are still getting the time from the database (which is not a pretty solution) to avoid clock skews which might happen.
We might ideally use the Java8 `Clock` so that we can mock it out in tests and use a fix timeframe, but that requires a broader change - publicauth needs some general refactoring anyway, so that could go on the list of todos.
with @alexbishop1
> PP-3061 Remove JodaTime in favour of Java 8 API

- Jenkinsfile
With publicauth ready for deployment into ECS, this adds a pipeline stage to the Jenkinsfile that will deploy to ECS as well as via the legacy method.
> PP-3095 Add pipeline stage to deploy to ECS

- pom.xml
* Upgraded Dropwizard to version 1.2.2:
* Since version 1.1.0, Dropwizard dropped dependency to `org.mockito`intentional. The Mockito dependency was only accidentally Maven's "compile" scope and has since moved into the correct "test" scope. See https://github.com/dropwizard/dropwizard/pull/1851 for details. Since Dropwizard itself has no dependency on Mockito except for its internal tests, a dependency to the latest stable version 2.15.0 had to be added to the project explicitly.  
* Removed explicit dependency of jersey version 2.25.1 which is not anymore needed since Dropwizard 1.2.2 already ships with that version. Note: jersey 2.25.1 is reported to have a medium vulnerability “XML Entity Expansion (XEE)” which has not yet been addressed in any subsequent version.
* Pinned Jackson to …
> PP-3350 Upgrade dropwizard to 1.2.x for Public Auth

- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
We'd like to have dropwizard metrics to measure the response times for each of our endpoints.
The metrics added by dropwizard for each endpoint are something like this:
```
"uk.gov.pay.publicauth.resources.PublicAuthResource.createTokenForAccount": {
"count": 89,
"max": 1.610663041,
"mean": 0.6122510077877983,
"min": 0.131364021,
"p50": 0.6673303650000001,
"p75": 0.7761138350000001,
"p95": 1.194686932,
"p98": 1.21974942,
"p99": 1.21974942,
"p999": 1.3611836130000001,
"stddev": 0.3178064275553258,
"m15_rate": 0.060280191333312604,
"m1_rate": 0.033173111988631133,
"m5_rate": 0.08651689402500556,
"mean_rate": 0.0663933806675867,
"duration_units": "seconds",
"rate_units": "calls/second"
}
```
> BAU - Add dropwizard metrics for each endpoint

- src/main/java/uk/gov/pay/publicauth/auth/Token.java
- src/main/java/uk/gov/pay/publicauth/auth/TokenAuthenticator.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/model/TokenHash.java
- src/main/java/uk/gov/pay/publicauth/model/TokenIdentifier.java
- src/main/java/uk/gov/pay/publicauth/model/TokenLink.java
- src/main/java/uk/gov/pay/publicauth/model/Tokens.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoTest.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceITest.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- We need to be able to revoke a token by hashed token itself rather
than token_link, this is because we are passing the hashed token between
products and the rest of the world
- also introduced models `TokenHash` and `TokenLink` to type strings
> PP-3816 Allow revoking a token by token_hash

- src/test/resources/logback.xml
We need to lower the logging level coming from the Apache HttpClient library because Apache httpclient by default logs everything at DEBUG level which is currently logging things that it shouldn't be logging.
Unfortunately adding the extra logging config to the yaml file used by Dropwizard does not work. It actually requires a logback.xml file.
> BAU Reduce logback log level

- build-local.sh
- pom.xml
Even though this is a milestone release, if it passes CI I don't see why we shouldn't use it?
> PP-4573: Upgrade failsafe maven plugin to 3.0.0-M3

- docker-startup.sh
Use environment variables to set JVM system properties for proxy configuration.
This makes the application respond to the following 3 environment variables:
http_proxy - passed as http.proxyHost
https_proxy - passed as https.proxyHost
java_http_non_proxy_hosts - passed as http.nonProxyHosts
> PP-4584: Manage HTTP proxies via env. vars

- pom.xml
This makes the .jar quite a lot smaller
> BAU: Mark dropwizard-testing as a test dependency

- pom.xml
We want to ensure nothing pulls in an old hamcrest-library, so list it before
other test dependencies in pom.xml
Also use the correct artifact ('hamcrest' instead of 'hamcrest-core')
> BAU: Move hamcrest above other test dependencies

- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
- Making the log lines look more like connector's by adding additional info
as to what is reported.
This helps in two way: searches are going to return more uniform results,
and we will have less noise when looking for errors. For example,`level=error`
will help isolating the `logger.error` lines rather than lower level ones which
simply have the word error in the message
> PP-4602 - change structure of loglines

- src/main/java/uk/gov/pay/publicauth/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResourceChecker.java
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
- src/test/java/uk/gov/pay/publicauth/filters/LoggingFilterTest.java
* Stop doing string concatenation
* Include relevant information in errors from TrustStoreLoader
* Stop logging the request ID in our messages - it's done via MDC and our
logFormat
> BAU: Clean up logging

- pom.xml
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResourceChecker.java
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
- src/main/java/uk/gov/pay/publicauth/util/TrustingSSLSocketFactory.java
* Refactor TrustStoreLoader to be more functional
* Move `dropwizard-testing` to test scope in the pom
* Remove unused `httpclient` dependency
* Reduce the amount of code used to wait for the database to come up
> BAU: Code cleanup

- pom.xml
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
Something isn't working quite right, so let's do a binary chop between release 111 and 112.
Reverts:
91684ac971a1f7e7c69a9ecd5b40caf2966ba1f7
29bd41fad5b4481a6eaf2c942ab5cda6a3adeee1
0cf5fb10afe78784bec27da09fc5d1b41f8d8891
91684ac971a1f7e7c69a9ecd5b40caf2966ba1f7
Retains:
7c141fcb7c68f4e2046a901180619903005ff7f9
23fa411dbed4bae658c484901d639f5aee7d8c77
git diff alpha_release-111..bau_revert_release_111
> BAU: Partially revert release 112

- pom.xml
This was added in 0cf4a6b4bdfa9fb7df64d6f90a6cc92cd9342b67 but never actually
used.
> BAU: Remove httpclient

- pom.xml
This should only be needed for running tests. Remove it from the runtime .jar
> Declare the dropwizard-testing dependency a test dependency

- pom.xml
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
* Reintroduce the `httpclient` dependency - `publicauth` was failing to start after removing it. No, I don't understand either.
* Reintroduce commit 29bd41fad5b4481a6eaf2c942ab5cda6a3adeee1 - it looks like this was not the source of our problems
> Re-add httpclient, refactor TrustStoreLoader

- docker-startup.sh
This will ensure proxy settings, memory limits etc. apply when waiting for the
database to come up as well as when applying database migrations.
Also, cope with JAVA_OPTS being unset.
> PP-4584: Pass JAVA_OPTS to all java invocations

- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResource.java
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResourceChecker.java
- src/main/java/uk/gov/pay/publicauth/util/DatabaseStartupResource.java
- src/main/java/uk/gov/pay/publicauth/util/DependentResourceWaitCommand.java
- src/test/java/uk/gov/pay/publicauth/util/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java
- src/test/java/uk/gov/pay/publicauth/utils/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java
Clean up the abstractions in this code - there are layers in here, but they know too much about each other.
Separate out the thing being checked (`ApplicationStartupDependentResource`) and the thing doing the checking (`ApplicationStartupDependentResourceChecker`)
Make the database checker an implementation of `ApplicationStartupDependentResource` and remove application-specific knowledge from it so we can use the code in other microservices as-is.
Also separate out the waiting part of the checker so we can mock it in tests.
Finally, put the tests in the same package as the things they are testing so that more things can be package-private.
Our end to end tests will test this quite thoroughly.
> PP-4616: Refactor code to poll  for database availability on startup

- pom.xml
- src/main/java/uk/gov/pay/publicauth/util/DependentResourceWaitCommand.java
Upgrade pay-java-commons to take advantage of an easier-to-use
implementation of ApplicationStartupDependentResourceChecker
> PP-4616: Use simpler ApplicationStartupDependentResourceChecker

- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
We weren't including the format placeholder in these log messages, so we would
never include details of the tokens we were dealing with.
Credit to lgtm.com
> Fix logging statements in PublicAuthResource

- README.md
- src/main/resources/config/config.yaml
This is the result of checking `docker-startup.sh` and the Dropwizard
configuration for all environment variables they use.
Also provide some sensible defaults for `PORT` and `ADMIN_PORT` in the
Dropwizard configuration, matching those set in the Dockerfile.
> PP-5075: Document all environment variables

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/healthcheck/DatabaseHealthCheck.java
Remove hardcoded references to `publicauth` from the database healthcheck code
Do the tests still pass?
Is the code nice?
> PP-5160: µsvc agnostic db healthcheck

- Jenkinsfile
- build-local.sh
- pom.xml
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/it/HealthCheckResourceIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
Integration tests are slow. They involve starting a PostgreSQL container and
instantiating Dropwizard.
Split them from the unit tests and run the unit tests with the surefire plugin
instead.
Rename integration tests to match the default include/exclude rules for the
surefire and failsafe maven plugins. By default, the failsafe plugin will
include any tests matching IT*.java, *IT.java and *ITCase.java. This was not
the naming scheme our integration tests had, so fix that.
Since unit tests are so quick, we no longer need to skip them when running
local builds.
maven's 'package' target doesn't include running integration tests, so switch
to using the 'verify' target during CI builds, which is what we should've been
doing anyway.
> Separate integration tests from unit tests

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/healthcheck/DatabaseHealthCheck.java
- src/main/java/uk/gov/pay/publicauth/service/DatabaseMetricsService.java
- src/main/java/uk/gov/pay/publicauth/service/DoublePostgresMetric.java
- src/main/java/uk/gov/pay/publicauth/service/LongPostgresMetric.java
- src/main/java/uk/gov/pay/publicauth/service/PostgresMetric.java
Move database metrics polling to a dedicated thread, rather than calculating them as a side-effect of the database healthcheck.
I tried testing this against a postgres container and it pulled metrics but they were all zeros (this might be fine)
If this is good, both the healthcheck code and the metrics code can move to `pay-java-commons`
Do we need to create our own thread? Is there already one we can use somewhere?
Is the thread polling at a sensible rate? (currently it's twice the rate at which we report in to graphite)
> REP-188: Calculate database metrics separately to healthchecks

- pom.xml
The Gson library is transitively pulled in via the uk.gov.pay:logging
dependency. However this was not actually pulled in because of a current Gson
dependency with the test scope. This caused the service to fail to start up
during the end to end test with
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/app/pay-publicauth-0.1-SNAPSHOT-allinone.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access …
```
> PP-5722: The Gson library is needed by the json logger

- src/main/resources/config/config.yaml
Configure server request logs to log in json format (this repo was missed when this was originally done)
Add an 'environment' field to the logs, so that it is possible to filter
by environment using a Splunk text search. Splunk does currently extract
the environment from the source if it is explicitly searched on using
e.g. the term 'environment="production-2"', but some of our reports use
a text search so will not pick up on all log lines.
The text search continues to work for many logs where the environment is
included in some way in the log message, but not for others where it
isn't so it makes sense to get rid of this ambiguity.
In the apps producing the logs, we get the environment from an
environment variable which is already configured for use by Sentry.
> PP-5777 Log requests in JSON and add environment field to logs

- pom.xml
- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- src/test/java/uk/gov/pay/publicauth/utils/DropwizardAppWithPostgresRule.java
- Upgrades dropwizard to v2.0.0 and jackson to latest version
- Added `dropwizard-dependencies` as parent as v2.0.0 upgrade doesn't specify transitive dependency versions anymore https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html
We can also include BOM for transitive dependency versions but versions can't be overridden and we may end up with multiple revisions of same library. For example, `jackson-version` current used is `2.10.2` but dropwizard uses `2.10.1`
- Upgraded dropwizard-sentry library too without which builds are failing with error `java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory.getFilterFactories()'`
- Fixes/changes for AuthTokenDao as per JDBI v3
- Fixes …
> PP-6001 Upgrade dropwizard

- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/model/CreateTokenRequest.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
Commit 1: Change the `createTokenForAccount` endpoint to use a `CreateTokenRequest` type with validation rather than a `JsonNode` being validated within the method body. 
Commit 2: Modify `AuthTokenDao.storeToken` to take the `CreateTokenRequest` type to reduce the number of parameters being passed.
> Pp 6002 replace json node with request type

- src/main/resources/config/config.yaml
We might run into situations where the database name is not
`publicauth`.
This is the same we do for the other apps.
- Check everything works as usual
> BAU: Allow overriding the database name

- Dockerfile
Updated the the root CA certificate in the container build in preparation for updating the certs installed on the RDS instances.
The combined cert bundle URL does not need to be updated as the URL has not changed, but the updated bundle will be downloaded at build time.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
- Rebuild containers and deploy to test environment
- Ensure app works with **NEW** CA root cert but **OLD** RDS certs. The new ca certs must be backward compatible.
- Schedule the cert update on the RDS instance.
> PP-5920: Update RDS root ca cert to 2019

- manifest.yml
- src/main/resources/env-map.yml
Use the env-map buildpack to extract the db credentials from the bound
publicauth-db cf service.
```
gds5062 > cf push --vars-file /Users/danworth/projects/gds/pay-omnibus/paas/env_variables/staging.yml --var token_db_bcrypt_salt=something
```
Then check the DB vars are set
```
cf ssh publicauth
/tmp/lifecycle/shell
env | grep DB
```
> PP-6085 Source db envs from bound db service

- manifest.yml
Correct the BCrypt salt env var name.
Check on staging that the name should be `TOKEN_DB_BCRYPT_SALT` with an 'R'.
> PP-6085 Correct env var name in manifest.yml

- manifest.yml
Binds the publicauth app running on PaaS to the publicauth-secret-service used to provision application creds added in alphagov/pay-omnibus#97.
> PP-6127: Bind CF app to credentials service

- Jenkinsfile
Description:
- Before we can turn off the direct debit smoke test we need to ensure that no pipeline calls it. This ensures that the publicauth Jenkins pipeline doesn't call the direct debit smoke Jenkins function
> PP-6763 - Remove direct debit smoke test from publicauth Jenkins pipeline

- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/model/TokenLink.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
This is so that we can add a model to represent the token responses and use the Jackson `ToStringSerializer` to serialize TokenLinks in this response object.
The existing `toString` method returned the formatted string 'token_link <tokenLinkValue>'. Update log lines/exteption messages to include the 'token_link ' substring so that it can be removed from the `toString` method.
> PP-7104 Use toString method of TokenLink to return value

- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/dao/TokenMapper.java
- src/main/java/uk/gov/pay/publicauth/json/DateTimeStringSerializer.java
- src/main/java/uk/gov/pay/publicauth/model/TokenEntity.java
- src/main/java/uk/gov/pay/publicauth/model/TokenResponse.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
Add `TokenEntity` object to represent a `token` retrieved from the database. For now, insertion doesn't use this entity.
This is to replace returning Maps from the DAO.
Add a `TokenResponse` object to represent the response to requests to get a token/tokens to replace building the response using a map.
> PP-7104 Refactor to use TokenEntity object

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/exception/TokenNotFoundException.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
Move code that accesses the DAO from `PublicAuthResource` into `TokenService`. Next step will be to alter the authorise resource method in order to completely remove accessing the DAO from the resource.
> PP-7104 Move code from resource to service

- pom.xml
- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/exception/TokenInvalidException.java
- src/main/java/uk/gov/pay/publicauth/exception/TokenInvalidExceptionMapper.java
- src/main/java/uk/gov/pay/publicauth/exception/TokenRevokedException.java
- src/main/java/uk/gov/pay/publicauth/exception/TokenRevokedExceptionMapper.java
- src/main/java/uk/gov/pay/publicauth/model/AuthResponse.java
- src/main/java/uk/gov/pay/publicauth/model/TokenEntity.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/fixture/TokenEntityFixture.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
Return token_link for a successful authorisation request so it can be
logged by public api.
For an authorisation attempt for a revoked token, respond with a 401
status and body containing error_identifier AUTH_TOKEN_REVOKED with the
token_link in the body so this can be logged by public api,
For an authorisation attempt for a non-existent token, respond with a
401 status and body containing error_identifier AUTH_TOKEN_INVALID
> PP-7104 Return token_link from authorisation requests

- src/main/java/uk/gov/pay/publicauth/model/CreateTokenRequest.java
- src/main/java/uk/gov/pay/publicauth/model/TokenAccountType.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
Parse `token_account_type` param in the create api key request body.
This could then be used by the API key generation algorithm when
prefixing the token.
This should be optional, if no param is provided the key should still be
created.
If anything other than 'live', 'LIVE', 'test', 'TEST' is provided the
request should `400`.
> PP-5236 Add token account type param to create request

- README.md
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
IFF an account type is provided in the create api key request, attach a
prefix part to the api key token. This prefix is then included in the
hash/ checksum.
API key authentication is called on almost every interaction with Pay, as this is a significant change to this code it should verified in test and staging environments against historic and new data before being released to production. 
In all environments:
- API key authentication works for existing API tokens without token prefix
- If an account type is provided on creating an API key, the appropriate prefix is included in the generated token
- If no account type is provided, no prefix is included
- API key authentication works with new API keys with prefixed token
> PP-5236 Optionally prefix API key tokens with human readable string

- src/main/java/uk/gov/pay/publicauth/json/DateTimeStringSerializer.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
Around the beginning or the end of the year, the week year (YYYY) is not always the same as what we usually think of as the year (yyyy).
> BAU — Use yyyy (year) instead of YYYY (week year) when formatting

- src/main/resources/migrations.xml
We're moving DB migration jobs to Concourse. This PR adds a dummy table to test that the migration job works as expected. [See the equivalent PR for Connector](https://github.com/alphagov/pay-connector/pull/2930).
We'll remove the table again in a subsequent PR.
> PP-7922: Test DB migration for Concourse job

- src/main/resources/migrations.xml
Once we've tested the new Concourse DB migration job for publicauth, we can drop the test table again.
[See the equivalent Connector PR here](https://github.com/alphagov/pay-connector/pull/2933).
> PP-7922: DB migration to remove Concourse test table

- Jenkinsfile
This should stop our builds from failing.
> [PP-8695] Kill ECS Deploy from Jenkinsfile

- pom.xml
- The Github UI is giving critical warnings for our Java apps with liquibase below v4.8.0. Patched liquibase to 4.12.0
> PP-9620 update liquibase

- .github/dependabot.yml
- ignoring liquibase is no longer required, remove it from dependabot yaml file.
> PP-9620 update dependabot yaml

- .github/workflows/run-tests.yml
- pom.xml
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/dao/TokenMapper.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/it/HealthCheckResourceIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- src/test/java/uk/gov/pay/publicauth/utils/DropwizardAppWithPostgresRule.java
- src/test/java/uk/gov/pay/publicauth/utils/PostgresTestContainersBase.java
- src/test/resources/it-migrations.xml
- fixed some timeywimey bugs:
- stopped mapping JDBC query responses to ZonedDateTime as Postgres is not storing timezone information and this was leading to some odd behaviour in tests when deserialising
- removed use of `java.sql.Timestamp` in TokenMapper due to confusing behaviour when converting to and from Instant
- removed use of `govuk/postgres:11`, baselining on architecture agnostic `postgres:11.16`
- updated test bases and rules to enable cross architecture support
- added integration tests specific liquibase changelog (`it-migrations.xml`) to initialise the database before migrations can be run
- updated GHA to use new postgres image
- added testcontainers to better handle the health check integration test
> PP-10004 M1 support for integration tests

- .github/workflows/run-tests.yml
- README.md
Add a check in the GitHub actions workflow that runs on PR builds to check whether there are uncommitted changes after running `mvn compile`. If there are, this suggests that there have been changes to the API specification and the OpenApi file has not been regenerated. Fail the build when uncommitted changes are detected.
> PP-10255 Check if there are uncommitted changes to OpenApi file

- .github/dependabot.yml
Dependabot is keen to update to `eclipse-temurin:20-jre` - we're happy with `11-jre` for the moment.
> BAU: Pin base images to Java v11

- README.md
- pom.xml
- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/app/config/PublicAuthConfiguration.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
1. Remove graphite metrics configuration and sending
2. Rename GRAPHITE_SENDING_PERIOD_SECONDS to METRICS_COLLECTION_PERIOD_SECONDS, and set it to the appropriate value.
Check build passes and explicitly allow e2e tests to complete
> PP-11228: Remove graphite metrics sending and config

- pom.xml
• Upgrade Dropwizard from 3.0.1 to 3.0.2
• Use more Maven BOMs for dependencies
• Separate dependencies into those imported from BOMs and others
> PP-11652 Upgrade from Dropwizard 3.0.1 to Dropwizard 3.0.2

- pom.xml
- Use Testcontainers BOM
- Move `commons-codec` into the right place in the POM because it uses a BOM
> BAU — Small tweaks to POM

- m1/arm64.Dockerfile
- Replaces symlink for m1 docker file as code build can't build with symlinks
```
#1 [internal] load build definition from arm64.Dockerfile
--
94 | ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2730447583/Dockerfile: no such file or directory
```
> PP-12728 Replace symlink with actual file for m1 build

- src/main/resources/migrations.xml
Add stored procedure check_and_execute which allows specifying SQL, the table, and expected number of rows affected. This should allow ad-hoc modifications to be done more safely since it will automatically error if the number of rows affected wasn't exactly what you had intended
This is based on the prior art in https://github.com/alphagov/pay-connector/pull/5451/ and the RFC https://github.com/alphagov/pay-architecture/discussions/147
- Locally run up pay local with this branch of connector `pay local up --cluster card --local publicauth`
- Once it's running run `docker exec -it publicauth_db psql -U publicauth`
- List the functions `\df` you'll see check_and_execute exists.
- Try out the stored proc:
```
publicauth=> CALL check_and_execute('DELETE FROM databasechangelog', …
```
> PP-13026: Add stored procedure to allow safer manual sql execution

- openapi/publicauth_spec.yaml
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
Currently the way to revoke an api key is via an [embedded form which contains the token
link](https://github.com/alphagov/pay-selfservice/blob/master/app/views/api-keys/_key.njk#L40-L42) on the API keys (`/account/{accountId}/api-keys`) page on selfservice.
However in the new simplified accounts world the revocation happens on a different page with URL
`/simplified/service/{SERVICE_EXTERNAL_ID}/account/{ACCOUNT_TYPE}/settings/api-keys/revoke/{tokenLink}`. This page shows the text 'Are you sure you want to revoke <api key description/name>?'. We thus need an endpoint in publicauth to get the api key by token link in order to show the key description/name. For security we should pass in the account id too.
> PP-12395: Get token by token link and account id

- pom.xml
Fails to connect to the DB on AWS. Mindlessly removed dependency that makes it available.
> PP-13657 fix connection error

- pom.xml
Since Dropwizard is using httpclient5, we should also upgrade the client used to connect to PostGreSQL
> PP-13657 upgrade httpclient

- .secrets.baseline
- openapi/publicauth_spec.yaml
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/model/CreateTokenRequest.java
- src/main/java/uk/gov/pay/publicauth/model/ServiceMode.java
- src/main/java/uk/gov/pay/publicauth/model/TokenEntity.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/fixture/TokenEntityFixture.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- add `service_mode` and `service_external_id` as optional fields to `CreateTokenRequest`
- add tests that these fields are saved to the database
- update deprecated `required = true` parameter in Swagger `Schema` annotations
> PP-12364 Add service_mode and service_external_id fields to CreateTokenRequest

- .secrets.baseline
- openapi/publicauth_spec.yaml
- src/main/java/uk/gov/pay/publicauth/model/CreateTokenRequest.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthRevokeTokenResourceIT.java
- add `NotNull` constraint to `service_mode` and `service_external_id` on `CreateTokenRequest`
> PP-14240 Make service_external_id and service_mode required when creating tokens

- src/main/resources/migrations.xml
- add db migration that sets columns `service_mode` and `service_external_id` in tokens table as non-nullable
> PP-14046 Set new columns in the tokens table to non-nullable in the public auth database schema
