- Jenkinsfile
- Explicit pull of docker image govukpay/postgres:9.4.4 in Maven Build step
> PP-2043 Explicit pull of docker image govukpay/postgres:9.4.4

- pom.xml
upgrade jackson-databind to a patched version
> Address CVE-2017-7525

- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
This is mainly to check if publicauth builds the latest version succesfully, after our last jenkins' blip.
> PP-2888 Remove unnecessary lambda

- Dockerfile
- docker-startup.sh
- run-with-chamber.sh
Align publicauth with the rest of the ECS microservices where we utilise
the RUN_APP and RUN_MIGRATION environment variables and chamber.
solo
> PP-3095 ECSify Publicauth in Test

- Jenkinsfile
Use new smoke test and explicitly tag, notify etc.
> PP-3438 Use new smoke test

- README.md
The actual implemented algorithm is quite complex. I thought it would be
helpful to have an explicit statement of the token generation and validation
algorithms.
> Clarify token hashing algorithms

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/app/config/PublicAuthConfiguration.java
- src/main/java/uk/gov/pay/publicauth/auth/TokenAuthenticator.java
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/publicauth/healthcheck/DatabaseHealthCheck.java
- src/main/java/uk/gov/pay/publicauth/model/TokenState.java
- src/main/java/uk/gov/pay/publicauth/resources/HealthCheckResource.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResource.java
- src/main/java/uk/gov/pay/publicauth/util/DependentResourceWaitCommand.java
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoTest.java
- src/test/java/uk/gov/pay/publicauth/filters/LoggingFilterTest.java
- src/test/java/uk/gov/pay/publicauth/it/HealthCheckResourceITest.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceITest.java
- src/test/java/uk/gov/pay/publicauth/resources/HealthCheckResourceTest.java
- src/test/java/uk/gov/pay/publicauth/service/RandomIdGeneratorTest.java
- src/test/java/uk/gov/pay/publicauth/service/TokenServiceTest.java
- src/test/java/uk/gov/pay/publicauth/utils/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- src/test/java/uk/gov/pay/publicauth/utils/DropwizardAppWithPostgresRule.java
- src/test/resources/config/test-it-config.yaml
* Update our usage of deprecated things to use non-deprecated things
* Silence most of liquibase output
* Eliminate a few things IntelliJ was unhappy about
> BAU: Eliminate IntelliJ warnings, clean up tests

- docker-startup.sh
We can rely entirely on JAVA_OPTS for this.
> PP-4584: Remove java-specific proxy env. vars

- Jenkinsfile
- src/main/java/uk/gov/pay/publicauth/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResource.java
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResourceChecker.java
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
- src/main/java/uk/gov/pay/publicauth/util/TrustingSSLSocketFactory.java
- src/test/java/uk/gov/pay/publicauth/filters/LoggingFilterTest.java
- src/test/java/uk/gov/pay/publicauth/utils/ApplicationStartupApplicationStartupDependentResourceCheckerTest.java
Clean up a bunch of things IntelliJ got snarky about
> BAU: IntelliJ-inspired code cleanup

- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
Make more use of functional patterns
Include the filesystem location which was searched when reporting failure to
find or process files.
> Refactor code for loading certificates into our TrustStore

- docker-startup.sh
- pom.xml
- src/main/java/uk/gov/pay/publicauth/filters/LoggingFilter.java
- src/main/java/uk/gov/pay/publicauth/util/ApplicationStartupDependentResourceChecker.java
- src/main/java/uk/gov/pay/publicauth/util/TrustStoreLoader.java
- src/main/java/uk/gov/pay/publicauth/util/TrustingSSLSocketFactory.java
- src/test/java/uk/gov/pay/publicauth/filters/LoggingFilterTest.java
Something is broken and I don't know what.
Revert all changes since release 105, except for changes to tests which are
passing and don't depend on changes to the application.
Also keep the Jenkinsfile as is - it seems fine.
`git diff alpha_release-105..origin/bau_revert_to_release_105`
> Partially revert to release 105

- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
The JCL can do what we want here. Also do less concatenation of Strings.
> BAU: Replace google Joiner with String.join()

- src/main/java/uk/gov/pay/publicauth/resources/HealthCheckResource.java
Replace iterative code with functional code in HealthCheckResource
We're transforming one `Map` into another and then making an assertion about the contents. This is something that lends itself to functional style really nicely and becomes more expressive as a result.
> BAU: Be more functional in HealthCheckResource

- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
- Cleanup whitespace in our Dropwizard configuration files
- Use the same logformat as other microservices
> PP-4602: Improve logging format

- src/test/java/uk/gov/pay/publicauth/utils/DropwizardAppWithPostgresRule.java
This is really a dummy commit to generate a release to test the pipeline, but
we might as well make some kind of improvement whilst doing it.
> Remove spurious blank line from DropwizardAppWithPostgresRule

- Dockerfile
- Jenkinsfile
- docker-startup.sh
- pom.xml
- Java 11 everywhere (container base image, Jenkins, pom )
- CI should pass
> PP-5054 Migrate to java11

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/app/config/PublicAuthConfiguration.java
We can get Dropwizard's configuration code to do the hard work for us here.
> Define the port number for graphite as an integer

- pom.xml
- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
_A brief description of the pull request:_
> PP-5722: Configure app to use structured logging

- pom.xml
This also fixes some security vulnerabilities
> bau: Upgrade jackson version

- pom.xml
_A brief description of the pull request:_
> Revert "Bump maven-jar-plugin from 3.1.2 to 3.2.0"

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
App wouldn't start because the logging factory wasn't registered.
> PP-5777 Fix request logging

- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/filters/LoggingMDCRequestFilter.java
- src/main/java/uk/gov/pay/publicauth/filters/LoggingMDCResponseFilter.java
Description:
- Adds GATEWAY_ACOUNT_ID to the MDC for logging
- There is no Google Guice DI so we create the classes directly
> PP-5894-Add-keys-to-MDC

- .travis.yml
Adds Travis CI configuration for running tests.
> Add .travis.yml CI config file

- Jenkinsfile
Pretty sure this isn't needed anymore.
> PP-6310 Remove explicit postgres pull

- openapi/publicauth_spec.yaml
- pom.xml
- src/main/java/uk/gov/pay/publicauth/model/AuthResponse.java
- src/main/java/uk/gov/pay/publicauth/model/CreateTokenRequest.java
- src/main/java/uk/gov/pay/publicauth/model/TokenResponse.java
- src/main/java/uk/gov/pay/publicauth/resources/HealthCheckResource.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/resources/openapi-config.yaml
- Added config and annotations to generate OpenAPI specs
- Generated OpenAPI specs
- Preview
> PP-9456 Generate OpenAPI specs

- pom.xml
Reverts alphagov/pay-publicauth#819
> Revert "Bump dropwizard.version from 2.0.29 to 2.1.0"

- pom.xml
- src/main/java/uk/gov/pay/publicauth/app/PublicAuthApp.java
- src/main/java/uk/gov/pay/publicauth/app/config/PublicAuthConfiguration.java
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.
> PP-11223: Set up prometheus metrics

- .github/dependabot.yml
Also format the file so that `yamllint` likes it (in a separate commit).
> PP-11652 Fix Dependabot config for ignoring Dropwizard 4

- .github/workflows/run-tests.yml
- src/test/java/uk/gov/pay/publicauth/utils/DropwizardAppWithPostgresExtension.java
Bump Postgres containers to 15.2, like we have in our real envs.
> PP-11895-upgrade-postgres-container

- Dockerfile
- build-local.sh
- m1/arm64.Dockerfile
- Updated Dockerfiles to add a stage to build jar files
> PP-11944 Make Dockerfile multistage

- .github/workflows/_run-tests.yml
- Checks if m1/arm64.Dockerfile is a manifest
> PP-12728 Add manifest check for m1 dockerfile

- .github/dependabot.yml
- Updated dependabot config to ignore eclipse-temurin versions > 21
> PP-12728 Update dependabot config

- openapi/publicauth_spec.yaml
- src/main/java/uk/gov/pay/publicauth/dao/AuthTokenDao.java
- src/main/java/uk/gov/pay/publicauth/resources/PublicAuthResource.java
- src/main/java/uk/gov/pay/publicauth/service/TokenService.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthRevokeTokenResourceIT.java
I intend to move all revoke tests from PublicAuthResourceIT into PublicAuthRevokeTokenResourceIT in a next PR.
> PP-12413: Endpoint to revoke all tokens for an account

- .secrets.baseline
- README.md
- src/main/resources/config/config.yaml
- src/test/resources/config/test-it-config.yaml
Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results
> PP-13145: Accept BIND_HOST env var and default to localhost

- README.md
- add a short explanation of token_link
> BAU update README

- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
We need to add a new endpoint, thought I'd take the opportunity to refactor this big test first.
> PP-12395: Refactor PublicAuthResourceIT

- pom.xml
Reverts alphagov/pay-publicauth#1391
> Revert "PP-13657 upgrade httpclient"

- pom.xml
Fine tune Dropwizard 4 bom dependencies.
> PP-13657  refine Dropwizard 4 migration

- src/main/resources/migrations.xml
- add `service_mode` column to `tokens` table with type `varchar(255)` 
- add `service_external_id` column to `tokens` table with type `varchar(255)`
> PP-12364 Add service_mode and service_external_id columns to tokens table

- src/main/resources/migrations.xml
- src/test/java/uk/gov/pay/publicauth/dao/AuthTokenDaoIT.java
- src/test/java/uk/gov/pay/publicauth/it/PublicAuthResourceIT.java
- src/test/java/uk/gov/pay/publicauth/utils/DatabaseTestHelper.java
- amend integration tests to include fields that will be set as non-nullable
- some refactoring of test helper methods
> PP-14046 Update integration tests to comply with non-null constraints
